// Generated by jextract

package me.eigenraven.sdl2panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$72 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$72() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "SDL_SetWindowTitle",
        constants$2.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "SDL_GetWindowTitle",
        constants$3.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "SDL_SetWindowIcon",
        constants$2.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "SDL_SetWindowData",
        constants$11.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "SDL_GetWindowData",
        constants$6.const$3
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER,
        JAVA_INT,
        JAVA_INT
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "SDL_SetWindowPosition",
        constants$72.const$5
    );
}


