// Generated by jextract

package me.eigenraven.sdl2panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$140 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$140() {}
    static final VarHandle const$0 = constants$138.const$3.varHandle(MemoryLayout.PathElement.groupElement("padding4"));
    static final StructLayout const$1 = MemoryLayout.structLayout(
        JAVA_INT.withName("type"),
        JAVA_INT.withName("timestamp"),
        JAVA_INT.withName("which"),
        JAVA_BYTE.withName("ball"),
        JAVA_BYTE.withName("padding1"),
        JAVA_BYTE.withName("padding2"),
        JAVA_BYTE.withName("padding3"),
        JAVA_SHORT.withName("xrel"),
        JAVA_SHORT.withName("yrel")
    ).withName("SDL_JoyBallEvent");
    static final VarHandle const$2 = constants$140.const$1.varHandle(MemoryLayout.PathElement.groupElement("type"));
    static final VarHandle const$3 = constants$140.const$1.varHandle(MemoryLayout.PathElement.groupElement("timestamp"));
    static final VarHandle const$4 = constants$140.const$1.varHandle(MemoryLayout.PathElement.groupElement("which"));
    static final VarHandle const$5 = constants$140.const$1.varHandle(MemoryLayout.PathElement.groupElement("ball"));
}


