// Generated by jextract

package me.eigenraven.sdl2panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$213 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$213() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "SDL_RenderDrawRectsF",
        constants$10.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "SDL_RenderFillRectF",
        constants$2.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "SDL_RenderFillRectsF",
        constants$10.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "SDL_RenderCopyF",
        constants$57.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "SDL_RenderCopyExF",
        constants$211.const$4
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "SDL_RenderGeometry",
        constants$205.const$2
    );
}


