// Generated by jextract

package me.eigenraven.sdl2panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$108 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$108() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "SDL_LockSensors",
        constants$3.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "SDL_UnlockSensors",
        constants$3.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "SDL_NumSensors",
        constants$13.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "SDL_SensorGetDeviceName",
        constants$8.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "SDL_SensorGetDeviceType",
        constants$7.const$5
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "SDL_SensorGetDeviceNonPortableType",
        constants$7.const$5
    );
}


