// Generated by jextract

package me.eigenraven.sdl2panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$46 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$46() {}
    static final VarHandle const$0 = constants$43.const$4.varHandle(MemoryLayout.PathElement.groupElement("Gshift"));
    static final VarHandle const$1 = constants$43.const$4.varHandle(MemoryLayout.PathElement.groupElement("Bshift"));
    static final VarHandle const$2 = constants$43.const$4.varHandle(MemoryLayout.PathElement.groupElement("Ashift"));
    static final VarHandle const$3 = constants$43.const$4.varHandle(MemoryLayout.PathElement.groupElement("refcount"));
    static final VarHandle const$4 = constants$43.const$4.varHandle(MemoryLayout.PathElement.groupElement("next"));
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "SDL_GetPixelFormatName",
        constants$8.const$5
    );
}


