// Generated by jextract

package me.eigenraven.sdl2panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$64 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$64() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "SDL_FillRects",
        constants$48.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "SDL_UpperBlit",
        constants$57.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "SDL_LowerBlit",
        constants$57.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "SDL_SoftStretch",
        constants$57.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "SDL_SoftStretchLinear",
        constants$57.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "SDL_UpperBlitScaled",
        constants$57.const$3
    );
}


