// Generated by jextract

package me.eigenraven.sdl2panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$94 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$94() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "SDL_JoystickOpen",
        constants$8.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "SDL_JoystickFromInstanceID",
        constants$8.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "SDL_JoystickFromPlayerIndex",
        constants$8.const$5
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(JAVA_INT,
        JAVA_INT,
        JAVA_INT,
        JAVA_INT,
        JAVA_INT
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "SDL_JoystickAttachVirtual",
        constants$94.const$3
    );
    static final StructLayout const$5 = MemoryLayout.structLayout(
        JAVA_SHORT.withName("version"),
        JAVA_SHORT.withName("type"),
        JAVA_SHORT.withName("naxes"),
        JAVA_SHORT.withName("nbuttons"),
        JAVA_SHORT.withName("nhats"),
        JAVA_SHORT.withName("vendor_id"),
        JAVA_SHORT.withName("product_id"),
        JAVA_SHORT.withName("padding"),
        JAVA_INT.withName("button_mask"),
        JAVA_INT.withName("axis_mask"),
        RuntimeHelper.POINTER.withName("name"),
        RuntimeHelper.POINTER.withName("userdata"),
        RuntimeHelper.POINTER.withName("Update"),
        RuntimeHelper.POINTER.withName("SetPlayerIndex"),
        RuntimeHelper.POINTER.withName("Rumble"),
        RuntimeHelper.POINTER.withName("RumbleTriggers"),
        RuntimeHelper.POINTER.withName("SetLED"),
        RuntimeHelper.POINTER.withName("SendEffect")
    ).withName("SDL_VirtualJoystickDesc");
}


