// Generated by jextract

package me.eigenraven.sdl2panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$162 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$162() {}
    static final VarHandle const$0 = constants$161.const$1.varHandle(MemoryLayout.PathElement.groupElement("data1"));
    static final VarHandle const$1 = constants$161.const$1.varHandle(MemoryLayout.PathElement.groupElement("data2"));
    static final StructLayout const$2 = MemoryLayout.structLayout(
        JAVA_INT.withName("type"),
        JAVA_INT.withName("timestamp"),
        RuntimeHelper.POINTER.withName("msg")
    ).withName("SDL_SysWMEvent");
    static final VarHandle const$3 = constants$162.const$2.varHandle(MemoryLayout.PathElement.groupElement("type"));
    static final VarHandle const$4 = constants$162.const$2.varHandle(MemoryLayout.PathElement.groupElement("timestamp"));
    static final VarHandle const$5 = constants$162.const$2.varHandle(MemoryLayout.PathElement.groupElement("msg"));
}


