// Generated by jextract

package me.eigenraven.sdl2panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$147 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$147() {}
    static final VarHandle const$0 = constants$146.const$0.varHandle(MemoryLayout.PathElement.groupElement("padding2"));
    static final VarHandle const$1 = constants$146.const$0.varHandle(MemoryLayout.PathElement.groupElement("padding3"));
    static final VarHandle const$2 = constants$146.const$0.varHandle(MemoryLayout.PathElement.groupElement("value"));
    static final VarHandle const$3 = constants$146.const$0.varHandle(MemoryLayout.PathElement.groupElement("padding4"));
    static final StructLayout const$4 = MemoryLayout.structLayout(
        JAVA_INT.withName("type"),
        JAVA_INT.withName("timestamp"),
        JAVA_INT.withName("which"),
        JAVA_BYTE.withName("button"),
        JAVA_BYTE.withName("state"),
        JAVA_BYTE.withName("padding1"),
        JAVA_BYTE.withName("padding2")
    ).withName("SDL_ControllerButtonEvent");
    static final VarHandle const$5 = constants$147.const$4.varHandle(MemoryLayout.PathElement.groupElement("type"));
}


