// Generated by jextract

package me.eigenraven.sdl2panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$171 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$171() {}
    static final VarHandle const$0 = constants$169.const$1.varHandle(MemoryLayout.PathElement.groupElement("attack_level"));
    static final VarHandle const$1 = constants$169.const$1.varHandle(MemoryLayout.PathElement.groupElement("fade_length"));
    static final VarHandle const$2 = constants$169.const$1.varHandle(MemoryLayout.PathElement.groupElement("fade_level"));
    static final StructLayout const$3 = MemoryLayout.structLayout(
        JAVA_SHORT.withName("type"),
        MemoryLayout.paddingLayout(16),
        MemoryLayout.structLayout(
            JAVA_BYTE.withName("type"),
            MemoryLayout.paddingLayout(24),
            MemoryLayout.sequenceLayout(3, JAVA_INT).withName("dir")
        ).withName("direction"),
        JAVA_INT.withName("length"),
        JAVA_SHORT.withName("delay"),
        JAVA_SHORT.withName("button"),
        JAVA_SHORT.withName("interval"),
        MemoryLayout.sequenceLayout(3, JAVA_SHORT).withName("right_sat"),
        MemoryLayout.sequenceLayout(3, JAVA_SHORT).withName("left_sat"),
        MemoryLayout.sequenceLayout(3, JAVA_SHORT).withName("right_coeff"),
        MemoryLayout.sequenceLayout(3, JAVA_SHORT).withName("left_coeff"),
        MemoryLayout.sequenceLayout(3, JAVA_SHORT).withName("deadband"),
        MemoryLayout.sequenceLayout(3, JAVA_SHORT).withName("center"),
        MemoryLayout.paddingLayout(16)
    ).withName("SDL_HapticCondition");
    static final VarHandle const$4 = constants$171.const$3.varHandle(MemoryLayout.PathElement.groupElement("type"));
    static final VarHandle const$5 = constants$171.const$3.varHandle(MemoryLayout.PathElement.groupElement("length"));
}


