// Generated by jextract

package me.eigenraven.sdl2panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$45 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$45() {}
    static final VarHandle const$0 = constants$43.const$4.varHandle(MemoryLayout.PathElement.groupElement("Amask"));
    static final VarHandle const$1 = constants$43.const$4.varHandle(MemoryLayout.PathElement.groupElement("Rloss"));
    static final VarHandle const$2 = constants$43.const$4.varHandle(MemoryLayout.PathElement.groupElement("Gloss"));
    static final VarHandle const$3 = constants$43.const$4.varHandle(MemoryLayout.PathElement.groupElement("Bloss"));
    static final VarHandle const$4 = constants$43.const$4.varHandle(MemoryLayout.PathElement.groupElement("Aloss"));
    static final VarHandle const$5 = constants$43.const$4.varHandle(MemoryLayout.PathElement.groupElement("Rshift"));
}


