// Generated by jextract

package me.eigenraven.sdl2panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$135 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$135() {}
    static final VarHandle const$0 = constants$134.const$4.varHandle(MemoryLayout.PathElement.groupElement("timestamp"));
    static final VarHandle const$1 = constants$134.const$4.varHandle(MemoryLayout.PathElement.groupElement("windowID"));
    static final VarHandle const$2 = constants$134.const$4.varHandle(MemoryLayout.PathElement.groupElement("which"));
    static final VarHandle const$3 = constants$134.const$4.varHandle(MemoryLayout.PathElement.groupElement("button"));
    static final VarHandle const$4 = constants$134.const$4.varHandle(MemoryLayout.PathElement.groupElement("state"));
    static final VarHandle const$5 = constants$134.const$4.varHandle(MemoryLayout.PathElement.groupElement("clicks"));
}


