// Generated by jextract

package me.eigenraven.sdl2panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$136 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$136() {}
    static final VarHandle const$0 = constants$134.const$4.varHandle(MemoryLayout.PathElement.groupElement("padding1"));
    static final VarHandle const$1 = constants$134.const$4.varHandle(MemoryLayout.PathElement.groupElement("x"));
    static final VarHandle const$2 = constants$134.const$4.varHandle(MemoryLayout.PathElement.groupElement("y"));
    static final StructLayout const$3 = MemoryLayout.structLayout(
        JAVA_INT.withName("type"),
        JAVA_INT.withName("timestamp"),
        JAVA_INT.withName("windowID"),
        JAVA_INT.withName("which"),
        JAVA_INT.withName("x"),
        JAVA_INT.withName("y"),
        JAVA_INT.withName("direction"),
        JAVA_FLOAT.withName("preciseX"),
        JAVA_FLOAT.withName("preciseY"),
        JAVA_INT.withName("mouseX"),
        JAVA_INT.withName("mouseY")
    ).withName("SDL_MouseWheelEvent");
    static final VarHandle const$4 = constants$136.const$3.varHandle(MemoryLayout.PathElement.groupElement("type"));
    static final VarHandle const$5 = constants$136.const$3.varHandle(MemoryLayout.PathElement.groupElement("timestamp"));
}


