// Generated by jextract

package me.eigenraven.sdl2panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$206 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$206() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "SDL_UnlockTexture",
        constants$4.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "SDL_RenderTargetSupported",
        constants$3.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "SDL_SetRenderTarget",
        constants$2.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "SDL_GetRenderTarget",
        constants$3.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "SDL_RenderSetLogicalSize",
        constants$5.const$1
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "SDL_RenderGetLogicalSize",
        constants$53.const$2
    );
}


