// Generated by jextract

package me.eigenraven.sdl2panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$71 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$71() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "SDL_GetWindowPixelFormat",
        constants$3.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "SDL_CreateWindow",
        constants$59.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "SDL_CreateWindowFrom",
        constants$3.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "SDL_GetWindowID",
        constants$3.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "SDL_GetWindowFromID",
        constants$8.const$5
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "SDL_GetWindowFlags",
        constants$3.const$5
    );
}


