// Generated by jextract

package me.eigenraven.sdl2panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$13 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$13() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "SDL_WaitThread",
        constants$2.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "SDL_DetachThread",
        constants$4.const$0
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(JAVA_INT);
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "SDL_TLSCreate",
        constants$13.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "SDL_TLSGet",
        constants$8.const$5
    );
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(SDL_TLSSet$destructor.class, "apply", constants$4.const$0);
}


