// Generated by jextract

package me.eigenraven.sdl2panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$96 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$96() {}
    static final VarHandle const$0 = constants$94.const$5.varHandle(MemoryLayout.PathElement.groupElement("product_id"));
    static final VarHandle const$1 = constants$94.const$5.varHandle(MemoryLayout.PathElement.groupElement("padding"));
    static final VarHandle const$2 = constants$94.const$5.varHandle(MemoryLayout.PathElement.groupElement("button_mask"));
    static final VarHandle const$3 = constants$94.const$5.varHandle(MemoryLayout.PathElement.groupElement("axis_mask"));
    static final VarHandle const$4 = constants$94.const$5.varHandle(MemoryLayout.PathElement.groupElement("name"));
    static final VarHandle const$5 = constants$94.const$5.varHandle(MemoryLayout.PathElement.groupElement("userdata"));
}


