// Generated by jextract

package me.eigenraven.sdl2panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$164 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$164() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "SDL_HasEvents",
        constants$65.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "SDL_FlushEvent",
        constants$31.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "SDL_FlushEvents",
        constants$32.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "SDL_PollEvent",
        constants$3.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "SDL_WaitEvent",
        constants$3.const$5
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "SDL_WaitEventTimeout",
        constants$5.const$3
    );
}


