// Generated by jextract

package me.eigenraven.sdl2panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$224 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$224() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "SDL_Vulkan_GetInstanceExtensions",
        constants$6.const$1
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "SDL_Vulkan_CreateSurface",
        constants$6.const$1
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "SDL_Vulkan_GetDrawableSize",
        constants$53.const$2
    );
    static final MemorySegment const$3 = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("/tmp/jextract$2849531975144086477.h");
    static final MemorySegment const$4 = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("SDL_ACCELEROMETER_AS_JOYSTICK");
    static final MemorySegment const$5 = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("SDL_ALLOW_ALT_TAB_WHILE_GRABBED");
}


