// Generated by jextract

package me.eigenraven.sdl2panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$168 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$168() {}
    static final VarHandle const$0 = constants$167.const$2.varHandle(MemoryLayout.PathElement.groupElement("button"));
    static final VarHandle const$1 = constants$167.const$2.varHandle(MemoryLayout.PathElement.groupElement("interval"));
    static final VarHandle const$2 = constants$167.const$2.varHandle(MemoryLayout.PathElement.groupElement("level"));
    static final VarHandle const$3 = constants$167.const$2.varHandle(MemoryLayout.PathElement.groupElement("attack_length"));
    static final VarHandle const$4 = constants$167.const$2.varHandle(MemoryLayout.PathElement.groupElement("attack_level"));
    static final VarHandle const$5 = constants$167.const$2.varHandle(MemoryLayout.PathElement.groupElement("fade_length"));
}


