// Generated by jextract

package me.eigenraven.sdl2panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$39 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$39() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "SDL_HasSSE2",
        constants$13.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "SDL_HasSSE3",
        constants$13.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "SDL_HasSSE41",
        constants$13.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "SDL_HasSSE42",
        constants$13.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "SDL_HasAVX",
        constants$13.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "SDL_HasAVX2",
        constants$13.const$2
    );
}


