// Generated by jextract

package me.eigenraven.sdl2panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$125 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$125() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "SDL_LoadDollarTemplates",
        constants$124.const$5
    );
    static final StructLayout const$1 = MemoryLayout.structLayout(
        JAVA_INT.withName("type"),
        JAVA_INT.withName("timestamp")
    ).withName("SDL_CommonEvent");
    static final VarHandle const$2 = constants$125.const$1.varHandle(MemoryLayout.PathElement.groupElement("type"));
    static final VarHandle const$3 = constants$125.const$1.varHandle(MemoryLayout.PathElement.groupElement("timestamp"));
    static final StructLayout const$4 = MemoryLayout.structLayout(
        JAVA_INT.withName("type"),
        JAVA_INT.withName("timestamp"),
        JAVA_INT.withName("display"),
        JAVA_BYTE.withName("event"),
        JAVA_BYTE.withName("padding1"),
        JAVA_BYTE.withName("padding2"),
        JAVA_BYTE.withName("padding3"),
        JAVA_INT.withName("data1")
    ).withName("SDL_DisplayEvent");
    static final VarHandle const$5 = constants$125.const$4.varHandle(MemoryLayout.PathElement.groupElement("type"));
}


