// Generated by jextract

package me.eigenraven.sdl2panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$66 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$66() {}
    static final VarHandle const$0 = constants$65.const$5.varHandle(MemoryLayout.PathElement.groupElement("format"));
    static final VarHandle const$1 = constants$65.const$5.varHandle(MemoryLayout.PathElement.groupElement("w"));
    static final VarHandle const$2 = constants$65.const$5.varHandle(MemoryLayout.PathElement.groupElement("h"));
    static final VarHandle const$3 = constants$65.const$5.varHandle(MemoryLayout.PathElement.groupElement("refresh_rate"));
    static final VarHandle const$4 = constants$65.const$5.varHandle(MemoryLayout.PathElement.groupElement("driverdata"));
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "SDL_GetNumVideoDrivers",
        constants$13.const$2
    );
}


