// Generated by jextract

package me.eigenraven.sdl2panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$141 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$141() {}
    static final VarHandle const$0 = constants$140.const$1.varHandle(MemoryLayout.PathElement.groupElement("padding1"));
    static final VarHandle const$1 = constants$140.const$1.varHandle(MemoryLayout.PathElement.groupElement("padding2"));
    static final VarHandle const$2 = constants$140.const$1.varHandle(MemoryLayout.PathElement.groupElement("padding3"));
    static final VarHandle const$3 = constants$140.const$1.varHandle(MemoryLayout.PathElement.groupElement("xrel"));
    static final VarHandle const$4 = constants$140.const$1.varHandle(MemoryLayout.PathElement.groupElement("yrel"));
    static final StructLayout const$5 = MemoryLayout.structLayout(
        JAVA_INT.withName("type"),
        JAVA_INT.withName("timestamp"),
        JAVA_INT.withName("which"),
        JAVA_BYTE.withName("hat"),
        JAVA_BYTE.withName("value"),
        JAVA_BYTE.withName("padding1"),
        JAVA_BYTE.withName("padding2")
    ).withName("SDL_JoyHatEvent");
}


