// Generated by jextract

package me.eigenraven.sdl2panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$150 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$150() {}
    static final VarHandle const$0 = constants$149.const$4.varHandle(MemoryLayout.PathElement.groupElement("timestamp"));
    static final VarHandle const$1 = constants$149.const$4.varHandle(MemoryLayout.PathElement.groupElement("which"));
    static final VarHandle const$2 = constants$149.const$4.varHandle(MemoryLayout.PathElement.groupElement("touchpad"));
    static final VarHandle const$3 = constants$149.const$4.varHandle(MemoryLayout.PathElement.groupElement("finger"));
    static final VarHandle const$4 = constants$149.const$4.varHandle(MemoryLayout.PathElement.groupElement("x"));
    static final VarHandle const$5 = constants$149.const$4.varHandle(MemoryLayout.PathElement.groupElement("y"));
}


