// Generated by jextract

package me.eigenraven.sdl2panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$55 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$55() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "SDL_IntersectFRectAndLine",
        constants$54.const$0
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(JAVA_INT,
        JAVA_INT,
        JAVA_INT,
        JAVA_INT,
        JAVA_INT,
        JAVA_INT,
        JAVA_INT
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "SDL_ComposeCustomBlendMode",
        constants$55.const$1
    );
    static final StructLayout const$3 = MemoryLayout.structLayout(
        JAVA_INT.withName("flags"),
        MemoryLayout.paddingLayout(32),
        RuntimeHelper.POINTER.withName("format"),
        JAVA_INT.withName("w"),
        JAVA_INT.withName("h"),
        JAVA_INT.withName("pitch"),
        MemoryLayout.paddingLayout(32),
        RuntimeHelper.POINTER.withName("pixels"),
        RuntimeHelper.POINTER.withName("userdata"),
        JAVA_INT.withName("locked"),
        MemoryLayout.paddingLayout(32),
        RuntimeHelper.POINTER.withName("list_blitmap"),
        MemoryLayout.structLayout(
            JAVA_INT.withName("x"),
            JAVA_INT.withName("y"),
            JAVA_INT.withName("w"),
            JAVA_INT.withName("h")
        ).withName("clip_rect"),
        RuntimeHelper.POINTER.withName("map"),
        JAVA_INT.withName("refcount"),
        MemoryLayout.paddingLayout(32)
    ).withName("SDL_Surface");
    static final VarHandle const$4 = constants$55.const$3.varHandle(MemoryLayout.PathElement.groupElement("flags"));
    static final VarHandle const$5 = constants$55.const$3.varHandle(MemoryLayout.PathElement.groupElement("format"));
}


