// Generated by jextract

package me.eigenraven.sdl2panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$78 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$78() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "SDL_SetWindowMouseRect",
        constants$2.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "SDL_GetWindowMouseRect",
        constants$3.const$0
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_FLOAT
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "SDL_SetWindowBrightness",
        constants$78.const$2
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(JAVA_FLOAT,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "SDL_GetWindowBrightness",
        constants$78.const$4
    );
}


