// Generated by jextract

package me.eigenraven.sdl2panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$145 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$145() {}
    static final VarHandle const$0 = constants$144.const$3.varHandle(MemoryLayout.PathElement.groupElement("which"));
    static final StructLayout const$1 = MemoryLayout.structLayout(
        JAVA_INT.withName("type"),
        JAVA_INT.withName("timestamp"),
        JAVA_INT.withName("which"),
        JAVA_INT.withName("level")
    ).withName("SDL_JoyBatteryEvent");
    static final VarHandle const$2 = constants$145.const$1.varHandle(MemoryLayout.PathElement.groupElement("type"));
    static final VarHandle const$3 = constants$145.const$1.varHandle(MemoryLayout.PathElement.groupElement("timestamp"));
    static final VarHandle const$4 = constants$145.const$1.varHandle(MemoryLayout.PathElement.groupElement("which"));
    static final VarHandle const$5 = constants$145.const$1.varHandle(MemoryLayout.PathElement.groupElement("level"));
}


