// Generated by jextract

package me.eigenraven.sdl2panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$139 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$139() {}
    static final VarHandle const$0 = constants$138.const$3.varHandle(MemoryLayout.PathElement.groupElement("which"));
    static final VarHandle const$1 = constants$138.const$3.varHandle(MemoryLayout.PathElement.groupElement("axis"));
    static final VarHandle const$2 = constants$138.const$3.varHandle(MemoryLayout.PathElement.groupElement("padding1"));
    static final VarHandle const$3 = constants$138.const$3.varHandle(MemoryLayout.PathElement.groupElement("padding2"));
    static final VarHandle const$4 = constants$138.const$3.varHandle(MemoryLayout.PathElement.groupElement("padding3"));
    static final VarHandle const$5 = constants$138.const$3.varHandle(MemoryLayout.PathElement.groupElement("value"));
}


