// Generated by jextract

package me.eigenraven.sdl2panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$189 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$189() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "SDL_hid_get_serial_number_string",
        constants$187.const$1
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_LONG
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "SDL_hid_get_indexed_string",
        constants$189.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "SDL_hid_ble_scan",
        constants$31.const$4
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "SDL_SetHintWithPriority",
        constants$10.const$5
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "SDL_SetHint",
        constants$2.const$0
    );
}


