// Generated by jextract

package me.eigenraven.sdl2panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$134 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$134() {}
    static final VarHandle const$0 = constants$133.const$0.varHandle(MemoryLayout.PathElement.groupElement("x"));
    static final VarHandle const$1 = constants$133.const$0.varHandle(MemoryLayout.PathElement.groupElement("y"));
    static final VarHandle const$2 = constants$133.const$0.varHandle(MemoryLayout.PathElement.groupElement("xrel"));
    static final VarHandle const$3 = constants$133.const$0.varHandle(MemoryLayout.PathElement.groupElement("yrel"));
    static final StructLayout const$4 = MemoryLayout.structLayout(
        JAVA_INT.withName("type"),
        JAVA_INT.withName("timestamp"),
        JAVA_INT.withName("windowID"),
        JAVA_INT.withName("which"),
        JAVA_BYTE.withName("button"),
        JAVA_BYTE.withName("state"),
        JAVA_BYTE.withName("clicks"),
        JAVA_BYTE.withName("padding1"),
        JAVA_INT.withName("x"),
        JAVA_INT.withName("y")
    ).withName("SDL_MouseButtonEvent");
    static final VarHandle const$5 = constants$134.const$4.varHandle(MemoryLayout.PathElement.groupElement("type"));
}


