// Generated by jextract

package me.eigenraven.sdl2panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$22 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$22() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "SDL_ReadLE32",
        constants$3.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "SDL_ReadBE32",
        constants$3.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "SDL_ReadLE64",
        constants$12.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "SDL_ReadBE64",
        constants$12.const$3
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(JAVA_LONG,
        RuntimeHelper.POINTER,
        JAVA_BYTE
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "SDL_WriteU8",
        constants$22.const$4
    );
}


