// Generated by jextract

package me.eigenraven.sdl2panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$196 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$196() {}
    static final VarHandle const$0 = constants$195.const$4.varHandle(MemoryLayout.PathElement.groupElement("buttonid"));
    static final VarHandle const$1 = constants$195.const$4.varHandle(MemoryLayout.PathElement.groupElement("text"));
    static final StructLayout const$2 = MemoryLayout.structLayout(
        JAVA_BYTE.withName("r"),
        JAVA_BYTE.withName("g"),
        JAVA_BYTE.withName("b")
    );
    static final VarHandle const$3 = constants$196.const$2.varHandle(MemoryLayout.PathElement.groupElement("r"));
    static final VarHandle const$4 = constants$196.const$2.varHandle(MemoryLayout.PathElement.groupElement("g"));
    static final VarHandle const$5 = constants$196.const$2.varHandle(MemoryLayout.PathElement.groupElement("b"));
}


