// Generated by jextract

package me.eigenraven.sdl2panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$223 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$223() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "SDL_QuitSubSystem",
        constants$31.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "SDL_WasInit",
        constants$7.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "SDL_Quit",
        constants$3.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "SDL_Vulkan_LoadLibrary",
        constants$3.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "SDL_Vulkan_GetVkGetInstanceProcAddr",
        constants$0.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "SDL_Vulkan_UnloadLibrary",
        constants$3.const$3
    );
}


