// Generated by jextract

package me.eigenraven.sdl2panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$43 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$43() {}
    static final VarHandle const$0 = constants$42.const$5.varHandle(MemoryLayout.PathElement.groupElement("ncolors"));
    static final VarHandle const$1 = constants$42.const$5.varHandle(MemoryLayout.PathElement.groupElement("colors"));
    static final VarHandle const$2 = constants$42.const$5.varHandle(MemoryLayout.PathElement.groupElement("version"));
    static final VarHandle const$3 = constants$42.const$5.varHandle(MemoryLayout.PathElement.groupElement("refcount"));
    static final StructLayout const$4 = MemoryLayout.structLayout(
        JAVA_INT.withName("format"),
        MemoryLayout.paddingLayout(32),
        RuntimeHelper.POINTER.withName("palette"),
        JAVA_BYTE.withName("BitsPerPixel"),
        JAVA_BYTE.withName("BytesPerPixel"),
        MemoryLayout.sequenceLayout(2, JAVA_BYTE).withName("padding"),
        JAVA_INT.withName("Rmask"),
        JAVA_INT.withName("Gmask"),
        JAVA_INT.withName("Bmask"),
        JAVA_INT.withName("Amask"),
        JAVA_BYTE.withName("Rloss"),
        JAVA_BYTE.withName("Gloss"),
        JAVA_BYTE.withName("Bloss"),
        JAVA_BYTE.withName("Aloss"),
        JAVA_BYTE.withName("Rshift"),
        JAVA_BYTE.withName("Gshift"),
        JAVA_BYTE.withName("Bshift"),
        JAVA_BYTE.withName("Ashift"),
        JAVA_INT.withName("refcount"),
        RuntimeHelper.POINTER.withName("next")
    ).withName("SDL_PixelFormat");
    static final VarHandle const$5 = constants$43.const$4.varHandle(MemoryLayout.PathElement.groupElement("format"));
}


