// Generated by jextract

package me.eigenraven.sdl2panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$156 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$156() {}
    static final VarHandle const$0 = constants$155.const$2.varHandle(MemoryLayout.PathElement.groupElement("dTheta"));
    static final VarHandle const$1 = constants$155.const$2.varHandle(MemoryLayout.PathElement.groupElement("dDist"));
    static final VarHandle const$2 = constants$155.const$2.varHandle(MemoryLayout.PathElement.groupElement("x"));
    static final VarHandle const$3 = constants$155.const$2.varHandle(MemoryLayout.PathElement.groupElement("y"));
    static final VarHandle const$4 = constants$155.const$2.varHandle(MemoryLayout.PathElement.groupElement("numFingers"));
    static final VarHandle const$5 = constants$155.const$2.varHandle(MemoryLayout.PathElement.groupElement("padding"));
}


