// Generated by jextract

package me.eigenraven.sdl2panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$161 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$161() {}
    static final VarHandle const$0 = constants$160.const$4.varHandle(MemoryLayout.PathElement.groupElement("timestamp"));
    static final StructLayout const$1 = MemoryLayout.structLayout(
        JAVA_INT.withName("type"),
        JAVA_INT.withName("timestamp"),
        JAVA_INT.withName("windowID"),
        JAVA_INT.withName("code"),
        RuntimeHelper.POINTER.withName("data1"),
        RuntimeHelper.POINTER.withName("data2")
    ).withName("SDL_UserEvent");
    static final VarHandle const$2 = constants$161.const$1.varHandle(MemoryLayout.PathElement.groupElement("type"));
    static final VarHandle const$3 = constants$161.const$1.varHandle(MemoryLayout.PathElement.groupElement("timestamp"));
    static final VarHandle const$4 = constants$161.const$1.varHandle(MemoryLayout.PathElement.groupElement("windowID"));
    static final VarHandle const$5 = constants$161.const$1.varHandle(MemoryLayout.PathElement.groupElement("code"));
}


