// Generated by jextract

package me.eigenraven.sdl2panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$57 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$57() {}
    static final VarHandle const$0 = constants$55.const$3.varHandle(MemoryLayout.PathElement.groupElement("list_blitmap"));
    static final VarHandle const$1 = constants$55.const$3.varHandle(MemoryLayout.PathElement.groupElement("map"));
    static final VarHandle const$2 = constants$55.const$3.varHandle(MemoryLayout.PathElement.groupElement("refcount"));
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(SDL_blit.class, "apply", constants$57.const$3);
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        constants$57.const$3
    );
}


