// Generated by jextract

package me.eigenraven.sdl2panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$44 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$44() {}
    static final VarHandle const$0 = constants$43.const$4.varHandle(MemoryLayout.PathElement.groupElement("palette"));
    static final VarHandle const$1 = constants$43.const$4.varHandle(MemoryLayout.PathElement.groupElement("BitsPerPixel"));
    static final VarHandle const$2 = constants$43.const$4.varHandle(MemoryLayout.PathElement.groupElement("BytesPerPixel"));
    static final VarHandle const$3 = constants$43.const$4.varHandle(MemoryLayout.PathElement.groupElement("Rmask"));
    static final VarHandle const$4 = constants$43.const$4.varHandle(MemoryLayout.PathElement.groupElement("Gmask"));
    static final VarHandle const$5 = constants$43.const$4.varHandle(MemoryLayout.PathElement.groupElement("Bmask"));
}


