// Generated by jextract

package me.eigenraven.sdl2panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$17 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$17() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(SDL_RWops.close.class, "apply", constants$3.const$5);
    static final VarHandle const$1 = constants$14.const$4.varHandle(MemoryLayout.PathElement.groupElement("close"));
    static final VarHandle const$2 = constants$14.const$4.varHandle(MemoryLayout.PathElement.groupElement("type"));
    static final UnionLayout const$3 = MemoryLayout.unionLayout(
        MemoryLayout.structLayout(
            RuntimeHelper.POINTER.withName("base"),
            RuntimeHelper.POINTER.withName("here"),
            RuntimeHelper.POINTER.withName("stop")
        ).withName("mem"),
        MemoryLayout.structLayout(
            RuntimeHelper.POINTER.withName("data1"),
            RuntimeHelper.POINTER.withName("data2")
        ).withName("unknown")
    );
    static final StructLayout const$4 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("base"),
        RuntimeHelper.POINTER.withName("here"),
        RuntimeHelper.POINTER.withName("stop")
    );
    static final VarHandle const$5 = constants$17.const$4.varHandle(MemoryLayout.PathElement.groupElement("base"));
}


