// Generated by jextract

package me.eigenraven.sdl2panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$111 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$111() {}
    static final VarHandle const$0 = constants$110.const$5.varHandle(MemoryLayout.PathElement.groupElement("bindType"));
    static final UnionLayout const$1 = MemoryLayout.unionLayout(
        JAVA_INT.withName("button"),
        JAVA_INT.withName("axis"),
        MemoryLayout.structLayout(
            JAVA_INT.withName("hat"),
            JAVA_INT.withName("hat_mask")
        ).withName("hat")
    );
    static final VarHandle const$2 = constants$111.const$1.varHandle(MemoryLayout.PathElement.groupElement("button"));
    static final VarHandle const$3 = constants$111.const$1.varHandle(MemoryLayout.PathElement.groupElement("axis"));
    static final StructLayout const$4 = MemoryLayout.structLayout(
        JAVA_INT.withName("hat"),
        JAVA_INT.withName("hat_mask")
    );
    static final VarHandle const$5 = constants$111.const$4.varHandle(MemoryLayout.PathElement.groupElement("hat"));
}


