// Generated by jextract

package me.eigenraven.sdl2panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$184 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$184() {}
    static final VarHandle const$0 = constants$183.const$1.varHandle(MemoryLayout.PathElement.groupElement("release_number"));
    static final VarHandle const$1 = constants$183.const$1.varHandle(MemoryLayout.PathElement.groupElement("manufacturer_string"));
    static final VarHandle const$2 = constants$183.const$1.varHandle(MemoryLayout.PathElement.groupElement("product_string"));
    static final VarHandle const$3 = constants$183.const$1.varHandle(MemoryLayout.PathElement.groupElement("usage_page"));
    static final VarHandle const$4 = constants$183.const$1.varHandle(MemoryLayout.PathElement.groupElement("usage"));
    static final VarHandle const$5 = constants$183.const$1.varHandle(MemoryLayout.PathElement.groupElement("interface_number"));
}


