// Generated by jextract

package me.eigenraven.sdl2panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$198 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$198() {}
    static final VarHandle const$0 = constants$197.const$1.varHandle(MemoryLayout.PathElement.groupElement("numbuttons"));
    static final VarHandle const$1 = constants$197.const$1.varHandle(MemoryLayout.PathElement.groupElement("buttons"));
    static final VarHandle const$2 = constants$197.const$1.varHandle(MemoryLayout.PathElement.groupElement("colorScheme"));
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "SDL_ShowMessageBox",
        constants$2.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "SDL_ShowSimpleMessageBox",
        constants$68.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "SDL_Metal_CreateView",
        constants$3.const$0
    );
}


