// Generated by jextract

package me.eigenraven.sdl2panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$84 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$84() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        JAVA_INT.withName("scancode"),
        JAVA_INT.withName("sym"),
        JAVA_SHORT.withName("mod"),
        MemoryLayout.paddingLayout(16),
        JAVA_INT.withName("unused")
    ).withName("SDL_Keysym");
    static final VarHandle const$1 = constants$84.const$0.varHandle(MemoryLayout.PathElement.groupElement("scancode"));
    static final VarHandle const$2 = constants$84.const$0.varHandle(MemoryLayout.PathElement.groupElement("sym"));
    static final VarHandle const$3 = constants$84.const$0.varHandle(MemoryLayout.PathElement.groupElement("mod"));
    static final VarHandle const$4 = constants$84.const$0.varHandle(MemoryLayout.PathElement.groupElement("unused"));
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "SDL_GetKeyboardFocus",
        constants$0.const$0
    );
}


