// Generated by jextract

package me.eigenraven.sdl2panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$98 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$98() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(SDL_VirtualJoystickDesc.Rumble.class, "apply", constants$97.const$5);
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        constants$97.const$5
    );
    static final VarHandle const$2 = constants$94.const$5.varHandle(MemoryLayout.PathElement.groupElement("Rumble"));
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(SDL_VirtualJoystickDesc.RumbleTriggers.class, "apply", constants$97.const$5);
    static final VarHandle const$4 = constants$94.const$5.varHandle(MemoryLayout.PathElement.groupElement("RumbleTriggers"));
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(SDL_VirtualJoystickDesc.SetLED.class, "apply", constants$48.const$5);
}


