// Generated by jextract

package me.eigenraven.sdl2panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$195 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$195() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(SDL_LogOutputFunction.class, "apply", constants$194.const$5);
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        constants$194.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "SDL_LogGetOutputFunction",
        constants$2.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "SDL_LogSetOutputFunction",
        constants$2.const$3
    );
    static final StructLayout const$4 = MemoryLayout.structLayout(
        JAVA_INT.withName("flags"),
        JAVA_INT.withName("buttonid"),
        RuntimeHelper.POINTER.withName("text")
    );
    static final VarHandle const$5 = constants$195.const$4.varHandle(MemoryLayout.PathElement.groupElement("flags"));
}


