// Generated by jextract

package me.eigenraven.sdl2panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$110 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$110() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "SDL_SensorGetInstanceID",
        constants$3.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "SDL_SensorGetData",
        constants$10.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "SDL_SensorGetDataWithTimestamp",
        constants$1.const$4
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "SDL_SensorClose",
        constants$4.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "SDL_SensorUpdate",
        constants$3.const$3
    );
    static final StructLayout const$5 = MemoryLayout.structLayout(
        JAVA_INT.withName("bindType"),
        MemoryLayout.unionLayout(
            JAVA_INT.withName("button"),
            JAVA_INT.withName("axis"),
            MemoryLayout.structLayout(
                JAVA_INT.withName("hat"),
                JAVA_INT.withName("hat_mask")
            ).withName("hat")
        ).withName("value")
    ).withName("SDL_GameControllerButtonBind");
}


