// Generated by jextract

package me.eigenraven.sdl2panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$197 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$197() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        MemoryLayout.sequenceLayout(5, MemoryLayout.structLayout(
            JAVA_BYTE.withName("r"),
            JAVA_BYTE.withName("g"),
            JAVA_BYTE.withName("b")
        )).withName("colors")
    );
    static final StructLayout const$1 = MemoryLayout.structLayout(
        JAVA_INT.withName("flags"),
        MemoryLayout.paddingLayout(32),
        RuntimeHelper.POINTER.withName("window"),
        RuntimeHelper.POINTER.withName("title"),
        RuntimeHelper.POINTER.withName("message"),
        JAVA_INT.withName("numbuttons"),
        MemoryLayout.paddingLayout(32),
        RuntimeHelper.POINTER.withName("buttons"),
        RuntimeHelper.POINTER.withName("colorScheme")
    );
    static final VarHandle const$2 = constants$197.const$1.varHandle(MemoryLayout.PathElement.groupElement("flags"));
    static final VarHandle const$3 = constants$197.const$1.varHandle(MemoryLayout.PathElement.groupElement("window"));
    static final VarHandle const$4 = constants$197.const$1.varHandle(MemoryLayout.PathElement.groupElement("title"));
    static final VarHandle const$5 = constants$197.const$1.varHandle(MemoryLayout.PathElement.groupElement("message"));
}


