// Generated by jextract

package me.eigenraven.sdl2panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$165 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$165() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "SDL_PushEvent",
        constants$3.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(SDL_EventFilter.class, "apply", constants$2.const$0);
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "SDL_SetEventFilter",
        constants$2.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "SDL_GetEventFilter",
        constants$2.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "SDL_AddEventWatch",
        constants$2.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "SDL_DelEventWatch",
        constants$2.const$3
    );
}


