// Generated by jextract

package me.eigenraven.sdl2panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$80 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$80() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(SDL_HitTest.class, "apply", constants$6.const$1);
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        constants$6.const$1
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "SDL_SetWindowHitTest",
        constants$6.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "SDL_FlashWindow",
        constants$5.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "SDL_DestroyWindow",
        constants$4.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "SDL_IsScreenSaverEnabled",
        constants$13.const$2
    );
}


