// Generated by jextract

package me.eigenraven.sdl2panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$218 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$218() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "SDL_IsTablet",
        constants$13.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "SDL_OnApplicationWillTerminate",
        constants$3.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "SDL_OnApplicationDidReceiveMemoryWarning",
        constants$3.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "SDL_OnApplicationWillResignActive",
        constants$3.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "SDL_OnApplicationDidEnterBackground",
        constants$3.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "SDL_OnApplicationWillEnterForeground",
        constants$3.const$3
    );
}


