// Generated by jextract

package me.eigenraven.sdl2panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$201 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$201() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "SDL_GetRenderDriverInfo",
        constants$68.const$0
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(JAVA_INT,
        JAVA_INT,
        JAVA_INT,
        JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "SDL_CreateWindowAndRenderer",
        constants$201.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "SDL_CreateRenderer",
        constants$63.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "SDL_CreateSoftwareRenderer",
        constants$3.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "SDL_GetRenderer",
        constants$3.const$0
    );
}


