// Generated by jextract

package me.eigenraven.sdl2panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$52 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$52() {}
    static final VarHandle const$0 = constants$51.const$2.varHandle(MemoryLayout.PathElement.groupElement("h"));
    static final StructLayout const$1 = MemoryLayout.structLayout(
        JAVA_FLOAT.withName("x"),
        JAVA_FLOAT.withName("y"),
        JAVA_FLOAT.withName("w"),
        JAVA_FLOAT.withName("h")
    ).withName("SDL_FRect");
    static final VarHandle const$2 = constants$52.const$1.varHandle(MemoryLayout.PathElement.groupElement("x"));
    static final VarHandle const$3 = constants$52.const$1.varHandle(MemoryLayout.PathElement.groupElement("y"));
    static final VarHandle const$4 = constants$52.const$1.varHandle(MemoryLayout.PathElement.groupElement("w"));
    static final VarHandle const$5 = constants$52.const$1.varHandle(MemoryLayout.PathElement.groupElement("h"));
}


