// Generated by jextract

package me.eigenraven.sdl2panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$221 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$221() {}
    static final VarHandle const$0 = constants$220.const$4.varHandle(MemoryLayout.PathElement.groupElement("minor"));
    static final VarHandle const$1 = constants$220.const$4.varHandle(MemoryLayout.PathElement.groupElement("patch"));
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "SDL_GetVersion",
        constants$4.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "SDL_GetRevision",
        constants$0.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "SDL_GetRevisionNumber",
        constants$13.const$2
    );
    static final StructLayout const$5 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("language"),
        RuntimeHelper.POINTER.withName("country")
    ).withName("SDL_Locale");
}


