// Generated by jextract

package me.eigenraven.sdl2panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$172 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$172() {}
    static final VarHandle const$0 = constants$171.const$3.varHandle(MemoryLayout.PathElement.groupElement("delay"));
    static final VarHandle const$1 = constants$171.const$3.varHandle(MemoryLayout.PathElement.groupElement("button"));
    static final VarHandle const$2 = constants$171.const$3.varHandle(MemoryLayout.PathElement.groupElement("interval"));
    static final StructLayout const$3 = MemoryLayout.structLayout(
        JAVA_SHORT.withName("type"),
        MemoryLayout.paddingLayout(16),
        MemoryLayout.structLayout(
            JAVA_BYTE.withName("type"),
            MemoryLayout.paddingLayout(24),
            MemoryLayout.sequenceLayout(3, JAVA_INT).withName("dir")
        ).withName("direction"),
        JAVA_INT.withName("length"),
        JAVA_SHORT.withName("delay"),
        JAVA_SHORT.withName("button"),
        JAVA_SHORT.withName("interval"),
        JAVA_SHORT.withName("start"),
        JAVA_SHORT.withName("end"),
        JAVA_SHORT.withName("attack_length"),
        JAVA_SHORT.withName("attack_level"),
        JAVA_SHORT.withName("fade_length"),
        JAVA_SHORT.withName("fade_level"),
        MemoryLayout.paddingLayout(16)
    ).withName("SDL_HapticRamp");
    static final VarHandle const$4 = constants$172.const$3.varHandle(MemoryLayout.PathElement.groupElement("type"));
    static final VarHandle const$5 = constants$172.const$3.varHandle(MemoryLayout.PathElement.groupElement("length"));
}


