// Generated by jextract

package me.eigenraven.sdl2panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct SDL_TextEditingExtEvent {
 *     Uint32 type;
 *     Uint32 timestamp;
 *     Uint32 windowID;
 *     char* text;
 *     Sint32 start;
 *     Sint32 length;
 * };
 * }
 */
public class SDL_TextEditingExtEvent {

    public static MemoryLayout $LAYOUT() {
        return constants$131.const$1;
    }
    public static VarHandle type$VH() {
        return constants$131.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * Uint32 type;
     * }
     */
    public static int type$get(MemorySegment seg) {
        return (int)constants$131.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * Uint32 type;
     * }
     */
    public static void type$set(MemorySegment seg, int x) {
        constants$131.const$2.set(seg, x);
    }
    public static int type$get(MemorySegment seg, long index) {
        return (int)constants$131.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void type$set(MemorySegment seg, long index, int x) {
        constants$131.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle timestamp$VH() {
        return constants$131.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * Uint32 timestamp;
     * }
     */
    public static int timestamp$get(MemorySegment seg) {
        return (int)constants$131.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * Uint32 timestamp;
     * }
     */
    public static void timestamp$set(MemorySegment seg, int x) {
        constants$131.const$3.set(seg, x);
    }
    public static int timestamp$get(MemorySegment seg, long index) {
        return (int)constants$131.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void timestamp$set(MemorySegment seg, long index, int x) {
        constants$131.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle windowID$VH() {
        return constants$131.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * Uint32 windowID;
     * }
     */
    public static int windowID$get(MemorySegment seg) {
        return (int)constants$131.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * Uint32 windowID;
     * }
     */
    public static void windowID$set(MemorySegment seg, int x) {
        constants$131.const$4.set(seg, x);
    }
    public static int windowID$get(MemorySegment seg, long index) {
        return (int)constants$131.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void windowID$set(MemorySegment seg, long index, int x) {
        constants$131.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle text$VH() {
        return constants$131.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * char* text;
     * }
     */
    public static MemorySegment text$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$131.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * char* text;
     * }
     */
    public static void text$set(MemorySegment seg, MemorySegment x) {
        constants$131.const$5.set(seg, x);
    }
    public static MemorySegment text$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$131.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void text$set(MemorySegment seg, long index, MemorySegment x) {
        constants$131.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle start$VH() {
        return constants$132.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * Sint32 start;
     * }
     */
    public static int start$get(MemorySegment seg) {
        return (int)constants$132.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * Sint32 start;
     * }
     */
    public static void start$set(MemorySegment seg, int x) {
        constants$132.const$0.set(seg, x);
    }
    public static int start$get(MemorySegment seg, long index) {
        return (int)constants$132.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void start$set(MemorySegment seg, long index, int x) {
        constants$132.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle length$VH() {
        return constants$132.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * Sint32 length;
     * }
     */
    public static int length$get(MemorySegment seg) {
        return (int)constants$132.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * Sint32 length;
     * }
     */
    public static void length$set(MemorySegment seg, int x) {
        constants$132.const$1.set(seg, x);
    }
    public static int length$get(MemorySegment seg, long index) {
        return (int)constants$132.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void length$set(MemorySegment seg, long index, int x) {
        constants$132.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, SegmentScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


