// Generated by jextract

package me.eigenraven.sdl2panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct {
 *     int value;
 * };
 * }
 */
public class SDL_atomic_t {

    public static MemoryLayout $LAYOUT() {
        return constants$4.const$5;
    }
    public static VarHandle value$VH() {
        return constants$5.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int value;
     * }
     */
    public static int value$get(MemorySegment seg) {
        return (int)constants$5.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int value;
     * }
     */
    public static void value$set(MemorySegment seg, int x) {
        constants$5.const$0.set(seg, x);
    }
    public static int value$get(MemorySegment seg, long index) {
        return (int)constants$5.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void value$set(MemorySegment seg, long index, int x) {
        constants$5.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, SegmentScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


