// Generated by jextract

package me.eigenraven.sdl2panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * typedef struct _SDL_GameController SDL_GameController;
 * }
 */
public final class SDL_GameController {

    // Suppresses default constructor, ensuring non-instantiability.
    private SDL_GameController() {}
}


