// Generated by jextract

package me.eigenraven.sdl2panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct {
 *     Uint32 format;
 *     int w;
 *     int h;
 *     int refresh_rate;
 *     void* driverdata;
 * };
 * }
 */
public class SDL_DisplayMode {

    public static MemoryLayout $LAYOUT() {
        return constants$65.const$5;
    }
    public static VarHandle format$VH() {
        return constants$66.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * Uint32 format;
     * }
     */
    public static int format$get(MemorySegment seg) {
        return (int)constants$66.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * Uint32 format;
     * }
     */
    public static void format$set(MemorySegment seg, int x) {
        constants$66.const$0.set(seg, x);
    }
    public static int format$get(MemorySegment seg, long index) {
        return (int)constants$66.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void format$set(MemorySegment seg, long index, int x) {
        constants$66.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle w$VH() {
        return constants$66.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int w;
     * }
     */
    public static int w$get(MemorySegment seg) {
        return (int)constants$66.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int w;
     * }
     */
    public static void w$set(MemorySegment seg, int x) {
        constants$66.const$1.set(seg, x);
    }
    public static int w$get(MemorySegment seg, long index) {
        return (int)constants$66.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void w$set(MemorySegment seg, long index, int x) {
        constants$66.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle h$VH() {
        return constants$66.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int h;
     * }
     */
    public static int h$get(MemorySegment seg) {
        return (int)constants$66.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int h;
     * }
     */
    public static void h$set(MemorySegment seg, int x) {
        constants$66.const$2.set(seg, x);
    }
    public static int h$get(MemorySegment seg, long index) {
        return (int)constants$66.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void h$set(MemorySegment seg, long index, int x) {
        constants$66.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle refresh_rate$VH() {
        return constants$66.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int refresh_rate;
     * }
     */
    public static int refresh_rate$get(MemorySegment seg) {
        return (int)constants$66.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int refresh_rate;
     * }
     */
    public static void refresh_rate$set(MemorySegment seg, int x) {
        constants$66.const$3.set(seg, x);
    }
    public static int refresh_rate$get(MemorySegment seg, long index) {
        return (int)constants$66.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void refresh_rate$set(MemorySegment seg, long index, int x) {
        constants$66.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle driverdata$VH() {
        return constants$66.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * void* driverdata;
     * }
     */
    public static MemorySegment driverdata$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$66.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * void* driverdata;
     * }
     */
    public static void driverdata$set(MemorySegment seg, MemorySegment x) {
        constants$66.const$4.set(seg, x);
    }
    public static MemorySegment driverdata$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$66.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void driverdata$set(MemorySegment seg, long index, MemorySegment x) {
        constants$66.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, SegmentScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


