// Generated by jextract

package me.eigenraven.sdl2panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * enum  (*SDL_AssertionHandler)(struct SDL_AssertData* data,void* userdata);
 * }
 */
public interface SDL_AssertionHandler {

    int apply(java.lang.foreign.MemorySegment data, java.lang.foreign.MemorySegment userdata);
    static MemorySegment allocate(SDL_AssertionHandler fi, SegmentScope scope) {
        return RuntimeHelper.upcallStub(constants$2.const$1, fi, constants$2.const$0, scope);
    }
    static SDL_AssertionHandler ofAddress(MemorySegment addr, SegmentScope scope) {
        MemorySegment symbol = MemorySegment.ofAddress(addr.address(), 0, scope);
        return (java.lang.foreign.MemorySegment _data, java.lang.foreign.MemorySegment _userdata) -> {
            try {
                return (int)constants$2.const$2.invokeExact(symbol, _data, _userdata);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


