// Generated by jextract

package me.eigenraven.sdl2panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * unsigned int (*SDL_TimerCallback)(unsigned int interval,void* param);
 * }
 */
public interface SDL_TimerCallback {

    int apply(int interval, java.lang.foreign.MemorySegment param);
    static MemorySegment allocate(SDL_TimerCallback fi, SegmentScope scope) {
        return RuntimeHelper.upcallStub(constants$220.const$0, fi, constants$68.const$0, scope);
    }
    static SDL_TimerCallback ofAddress(MemorySegment addr, SegmentScope scope) {
        MemorySegment symbol = MemorySegment.ofAddress(addr.address(), 0, scope);
        return (int _interval, java.lang.foreign.MemorySegment _param) -> {
            try {
                return (int)constants$220.const$1.invokeExact(symbol, _interval, _param);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


