// Generated by jextract

package me.eigenraven.sdl2panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct SDL_HapticDirection {
 *     Uint8 type;
 *     Sint32 dir[3];
 * };
 * }
 */
public class SDL_HapticDirection {

    public static MemoryLayout $LAYOUT() {
        return constants$167.const$0;
    }
    public static VarHandle type$VH() {
        return constants$167.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * Uint8 type;
     * }
     */
    public static byte type$get(MemorySegment seg) {
        return (byte)constants$167.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * Uint8 type;
     * }
     */
    public static void type$set(MemorySegment seg, byte x) {
        constants$167.const$1.set(seg, x);
    }
    public static byte type$get(MemorySegment seg, long index) {
        return (byte)constants$167.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void type$set(MemorySegment seg, long index, byte x) {
        constants$167.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment dir$slice(MemorySegment seg) {
        return seg.asSlice(4, 12);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, SegmentScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


