// Generated by jextract

package me.eigenraven.sdl2panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct SDL_Keysym {
 *     SDL_Scancode scancode;
 *     SDL_Keycode sym;
 *     Uint16 mod;
 *     Uint32 unused;
 * };
 * }
 */
public class SDL_Keysym {

    public static MemoryLayout $LAYOUT() {
        return constants$84.const$0;
    }
    public static VarHandle scancode$VH() {
        return constants$84.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * SDL_Scancode scancode;
     * }
     */
    public static int scancode$get(MemorySegment seg) {
        return (int)constants$84.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * SDL_Scancode scancode;
     * }
     */
    public static void scancode$set(MemorySegment seg, int x) {
        constants$84.const$1.set(seg, x);
    }
    public static int scancode$get(MemorySegment seg, long index) {
        return (int)constants$84.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void scancode$set(MemorySegment seg, long index, int x) {
        constants$84.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle sym$VH() {
        return constants$84.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * SDL_Keycode sym;
     * }
     */
    public static int sym$get(MemorySegment seg) {
        return (int)constants$84.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * SDL_Keycode sym;
     * }
     */
    public static void sym$set(MemorySegment seg, int x) {
        constants$84.const$2.set(seg, x);
    }
    public static int sym$get(MemorySegment seg, long index) {
        return (int)constants$84.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void sym$set(MemorySegment seg, long index, int x) {
        constants$84.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle mod$VH() {
        return constants$84.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * Uint16 mod;
     * }
     */
    public static short mod$get(MemorySegment seg) {
        return (short)constants$84.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * Uint16 mod;
     * }
     */
    public static void mod$set(MemorySegment seg, short x) {
        constants$84.const$3.set(seg, x);
    }
    public static short mod$get(MemorySegment seg, long index) {
        return (short)constants$84.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void mod$set(MemorySegment seg, long index, short x) {
        constants$84.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle unused$VH() {
        return constants$84.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * Uint32 unused;
     * }
     */
    public static int unused$get(MemorySegment seg) {
        return (int)constants$84.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * Uint32 unused;
     * }
     */
    public static void unused$set(MemorySegment seg, int x) {
        constants$84.const$4.set(seg, x);
    }
    public static int unused$get(MemorySegment seg, long index) {
        return (int)constants$84.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void unused$set(MemorySegment seg, long index, int x) {
        constants$84.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, SegmentScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


